### ISSUE TITLE
bad cursor position on error

### ISSUE THREAD

**Issue by siegebell** [siegebell/vscoq#115]
Stepping forward, if there is an error, the cursor focus is currently set to the prior good state location. This is disorienting for errors on very long sentences.

Ideas
* either the cursor should not more or it should focus on the error
* the editor viewport should show the error
* maybe popup the error message in code (like pressing F8)

**Comment by aa755** [comment]
I had the same dilemma in my (now defunct) NetBeans plugin for Coq. I ended up having a user option to choose between 2 behaviors:

1. Neither the Cursor nor the viewport moves.
2. The cursor moves to the start position of the error.

Both options have usecases. When making merely fixes to a .v file that used to compile and now fails because of some minor change (e.g. some definition changed), the former mode saves a lot of time.
In those cases, typically the fixes were needed at the error position.
In contrast, sometimes, the fix for a problem needs to happen at a location that is different from the location of the error. In such cases, the cursor jump is annoying and causes extra work.

**Comment by siegebell** [comment]
Behavior 1 is an option that is already supported: put `"coq.moveCursorToFocus": false` in your settings to prevent moving the cursor when the state changes. Command `extension.coq.moveCursorToFocus` (default binding: `ctrl+alt+.`) moves the cursor to the current focused state, and "Go to Next Error or Warning"/`F8` cycles error positions.
