### ISSUE TITLE
Opening a file URL with macOS open ignores query parameters

### ISSUE THREAD

**Issue by tchajed** [siegebell/vscoq#96]
The standard way to open a URL in the default browser in macOS is the `open` command. Unfortunately, `open` actually understands URIs and ignores query parameters for the `file://` protocol. This results in the `html_views/goals/Coq.html` file being loaded without the necessary hostname and port.

It seems the only real solution to this is to serve that file from a local webserver and open that server's address instead of a file.

**Comment by tchajed** [comment]
I should mention that this is easy to workaround: the full URL is logged to the console; Help > Toggle Developer Tools will show it.

**Comment by siegebell** [comment]
This issue also exists with Window's `start` command. But you can instead specify "firefox ${url}" or "chrome ${url}" via `coq.externalViewUrlCommand`, for example; these programs do preserve the query parameters or the `file:///` Url.

I'll close this issue when I've implemented a webserver to host the pages.

**Comment by tchajed** [comment]
It's awkward on macOS to refer to the binaries (they're not provided on the $PATH by default), but calling them directly does work. Specifically, I'm now using

`"coq.externalViewUrlCommand": "'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' ${url}"`

which correctly opens URLs with parameters, and re-uses the existing Chrome instance.

I think it's fair enough to document this for macOS and close this issue, and have a separate (low priority) task of serving the page with a webserver, especially if this is the only problem you're running into with a `file:///` path.

**Comment by siegebell** [comment]
@tchajed I've added some info on this in the wiki's "Tips", and the autocomplete for `coq.externalViewUrlCommand` in settings.json now suggests the chrome command for OSX (among some other options).

Also, I went ahead and implemented the webserver (pretty trivial in Node.js) because this is just going to confuse most users unless the default option "just works." The default for `coq.externalViewUrlCommand` is now `"${url}"`, which will use OSX's `"open"`, Window's `"start"`, and Linux's `"xdg-open"`.
